### PR TITLE
pyon: faster processing of ndarrays

### PR DESCRIPTION
**Pull request by airwoodix**
When dealing with large arrays, ``sync_struct`` and other RPC is pretty slow, which can be limiting (see e.g. m-labs/artiq#1128). 
This patch addresses part of the issue by providing faster serialization of large NumPy arrays.

Test code (timings obtained with IPython `%timeit` on the `pyon.encode` and `pyon.decode` lines):

```python
from sipyco import pyon
import numpy as np


raw = np.random.sample(int(1e7))

packed = pyon.encode(raw)
unpacked = pyon.decode(packed)

assert np.array_equal(unpacked, raw)
```

Profile without this patch:

profile-orig

```
pyon.encode: 883 ms ± 3.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
pyon.decode: 853 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Encoding is dominated by calls to `encode_bytes()` which calls `repr()` on a bytes from `base64encode()`. Hard-coding the bytes representation kills this problem:

profile-bytes-encoding

```
pyon.encode: 199 ms ± 246 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
pyon.decode: 861 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Going for a faster base64 encoder ([pybase64](https://github.com/mayeut/pybase64)) offers a more marginal but easy profit (also applicable to deserialization):

profile-pybase64

```
pyon.encode: 121 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
pyon.decode: 682 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
The dependency to [pybase64](https://github.com/mayeut/pybase64) is optional. Using `validate=True` as recommended in the readme gives a ca. 10 ms speed-up in this scenario. It's irrelevant since base64 decoding is not the limiting factor in `pyon.decode`.

I'm not sure what the remaining time spent in `encode_ndarray()` is made of. The profiler is surprisingly silent... String formatting (f-string) or `StringIO` buffering don't overperform string concatenation. The serializations of the shape and the dtype are negligible (one could use `repr(x.shape)` directly since we know that the shape is an tuple in integers but it doesn't really help further).

``pyon.decode`` is clearly dominated by the call to `eval()`. Any ideas of something easy and non-breaking one could do to improve on this?

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
I would just make it a hard dependency. Otherwise it'll just create inconsistent performance results, and make the code a bit more complicated than it could be.

**Comment by sbourdeauducq** [comment]
There's no py35 conda package for pybase64, so artiq-legacy will have to keep using the older sipyco version. How is your nix-fu?

**Comment by airwoodix** [comment]
> I would just make it a hard dependency.

Fixed in 5f05040.

> There's no py35 conda package for pybase64, so artiq-legacy will have to keep using the older sipyco version.

Is this still an issue? (Python 3.5 is anyway EOL)

**Comment by sbourdeauducq** [comment]
> Is this still an issue?

Definitely. Many labs are still using ARTIQ-5.

> (Python 3.5 is anyway EOL)

Yes, just like Windows is a shitty OS, but most people are still using it.

**Comment by airwoodix** [comment]
Would it be an option to make an ad-hoc package, like for ``qasync``, ``pythonparser`` and others? Or was my quick scan of ``nix-scripts`` too fast?
Otherwise, if packaging is too annoying, one could also skip this part of the patch as it only brings 10% extra (but with negligible complexity in the code).

**Comment by sbourdeauducq** [comment]
It is an option, but that's not easier than keeping the older sipyco version on the stable channels.

**Comment by airwoodix** [comment]
> How is your nix-fu?

I'm not quite sure what would need to be done, so I'd say "not good enough".

I'd nevertheless be very happy to see this patch merged. How would you like to proceed?

**Comment by sbourdeauducq** [comment]
This patch when merged will break the CI for Windows and possibly Windows user installations. Sorry I do not have time currently to fix it for you.

**Comment by sbourdeauducq** [comment]
It's merged, but there will be conda problems when the package source is updated.

**Pull request merged**
